- name: Bootstrap Timescale cluster on access nodes
  hosts: timescale_access_nodes
  tasks:
  - name: Grant FDW privileges to Timescale user
    become: true
    become_user: postgres
    community.postgresql.postgresql_privs:
      database: "{{ timescale_database_name }}"
      privs: USAGE
      type: foreign_data_wrapper
      objs: timescaledb_fdw
      roles: "{{ timescale_username }}"

  - name: Gather facts from data nodes
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: true
    loop: "{{ groups['timescale_data_nodes'] }}"

  - name: Add data nodes
    include_tasks: tasks/timescale-add-data-node.yml
    vars:
      node_name: "{{ hostvars[item]['ansible_hostname'] }}"
      node_host: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      node_database: "{{ hostvars[item]['timescale_database_name'] | default(omit) }}"
    loop: "{{ groups['timescale_data_nodes'] }}"
