- name: Install Timescale repository key
  apt_key:
    url:  https://packagecloud.io/timescale/timescaledb/gpgkey

- name: Install Timescale repository
  apt_repository:
    repo: "deb https://packagecloud.io/timescale/timescaledb/debian/ {{ ansible_distribution_release }} main"
    update_cache: yes

- name: Install Timescale packages
  apt:
    state: present
    pkg: "{{ timescale_packages }}"

- name: Tune Timescale
  shell: timescaledb-tune -yes
  notify: restart postgresql

- name: Configure PostgreSQL for Timescale
  template:
    src: timescale.conf.j2
    dest: "{{ postgresql_conf_path }}/conf.d/timescale.conf"
    owner: postgres
    group: postgres
  notify: reload postgresql

- name: Create Timescale user
  community.postgresql.postgresql_user:
    name: "{{ timescale_username }}"
    password: "{{ timescale_password }}"
    # SUPERUSER to create the Promscale extension because it cannot be created beforehand
    role_attr_flags: SUPERUSER,CREATEROLE,NOCREATEDB,INHERIT,LOGIN,REPLICATION,NOBYPASSRLS
  become: true
  become_user: postgres

- name: Create Timescale database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ timescale_database_name }}"
    owner: "{{ timescale_username }}"

- name: Create Timescale extension
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: timescaledb
    db: "{{ timescale_database_name }}"

- name: Configure Timescale passfile
  template:
    src: .pgpass
    dest: /var/lib/postgresql/.pgpass
    owner: postgres
    group: postgres
    mode: '0600'
